version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    build:
      context: .
      dockerfile: dev-dockerfile
    image: app-backend:dev
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "node", "server.js"]
    environment:
      - DJANGO_SETTINGS_MODULE=myapp.settings
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
