version: '3.7'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
      - .:/usr/src/nourished-backend
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nourished_dev
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: dev-dockerfile
    image: app-backend:dev
    environment:
      - DEBUG=${DEBUG}
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "node", "server.js"]
    environment:
      - NODE_ENV=development
      - DB_HOST=db
    volumes:
      - .:/usr/src/nourished-backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  migration:
    image: app-backend:dev
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "npm", "run", "migrate"]
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - PGPASSWORD=postgres
    depends_on:
      - db
    links:
      - db
