version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: "Storing JWT creds"
                command: env JWT_RSA=${JWT_RSA} JWT_RSA_PUB=${JWT_RSA_PUB} bash scripts/reload-jwt.sh
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test