version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    working_directory: ~/nourished-backend
    docker:
      - image: circleci/node:13.12   
      - image: circleci/postgres:alpine
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: nourished_test
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: "Storing JWT creds"
                command: env JWT_RSA="Tedt1" JWT_RSA_PUB="Test1" bash scripts/reload-jwt.sh
            - run: 
                name: "Retrieving JWT creds"
                command: cat config/jwttokens/jwt_rsa
            - run:
                name: install dockerize
                command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
                environment:
                  DOCKERIZE_VERSION: v0.3.0
            - run:
                name: Wait for db
                command: dockerize -wait tcp://localhost:5432 -timeout 1m
            - run: npm install
            - run:
                name: "Create the db migrations"
                command: node seeders/migrate.js
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build